### ISSUE TITLE
Change of source doesn't work

### ISSUE THREAD

**Issue by LeoeLeoeL** [simbaja/ha_oppoudp#1]
The selection available showed in the picture
![image](https://user-images.githubusercontent.com/65825223/154811694-54c7eb31-ddf4-40fa-8477-929629053430.png)
doesn't work.
HA return the following message in the log:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/oppo_udp/media_player.py:397
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:19:15 (2 occurrences)
Last logged: 18:19:23

[140284833589808] 'Hdmi In'
[140284833589808] 'Hdmi Arc'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 190, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/oppo_udp/media_player.py", line 397, in async_select_source
    await self.device.async_set_input_source(SetInputSource[source])
  File "/usr/local/lib/python3.9/enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'Hdmi In'

**Comment by LeoeLeoeL** [comment]
excuse me, is it useful to write here?

**Comment by simbaja** [comment]
I do see it; however, I'm absolutely slammed with work at the moment and haven't had a chance to review and resolve.  My apologies.

**Comment by LeoeLeoeL** [comment]
Tks for answering.
Don't worry, take your time.

**Comment by 35gh** [comment]
Hi @simbaja, would you be able to look into this issue? Are you still supporting this integration? Thank you!

**Comment by simbaja** [comment]
I just pushed an update, haven't had a chance to test it though as I've been traveling from work and away from my device.  Hope it helps.

**Comment by LeoeLeoeL** [comment]
It works!
Tks
