### ISSUE TITLE
Improve handling of non connected devices: set state to "unavailable" rather than "unknown"

### ISSUE THREAD

**Issue by 35gh** [simbaja/ha_oppoudp#10]
Hi,

First, thank you for the latest changes to remove deprecations. Would it be possible to make a new release with the latest commits and bump the integration version to get it updated automatically via HACS?

With regards of this ticket, warnings appear in logs when a player is not connected/switched off:
`Enregistreur: oppoudpsdk.client
Source: runner.py:189
S'est produit pour la première fois: 12:38:29 (18 occurrences)
Dernier enregistrement: 12:40:34
Unhandled exception before successful connect: [Errno 113] Connect call failed ('192.168.1.10', 23)`

Would it be possible to change the state to "Unavailable" rather than "Unknown" (and eventually retry periodically), and raise an error in the Devices section?

Similar to other player integrations. For example the "Frontier Silicon" integration from HA Core:

<img width="1081" alt="Capture d’écran 2024-11-15 à 12 44 51" src="https://github.com/user-attachments/assets/5cfdc88b-5044-4d67-8041-e9d28773422c">

<img width="670" alt="Capture d’écran 2024-11-15 à 12 51 08" src="https://github.com/user-attachments/assets/4d933d30-cae3-483f-a62e-c66696417e10">

<img width="619" alt="Capture d’écran 2024-11-15 à 12 48 56" src="https://github.com/user-attachments/assets/4264800e-a08e-465a-9853-a4b26347438d">

Thank you!

**Comment by simbaja** [comment]
New release has been created.  In regards to the availability, it might be a while before I can get to it (have a lot going on at the moment).  Not sure if you have time/capability, but would welcome any PRs to implement this.

**Comment by dekoskytasdebolle** [comment]
Thanks for making the new release! It works for my use case in Home Assistant now.

I've been trying to reproduce the reported error of this issue. But my player reports it's `off` now as expected. But I see some other errors regarding mediaplayer states in my logs as well. 

```Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/oppoudpsdk/device.py", line 248, in _on_message_received
    await self._handle_play_response(response.status)
                                     ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/oppoudpsdk/response/response.py", line 88, in status
    return PlayStatus(self._parameters[0])
  File "/usr/local/lib/python3.13/enum.py", line 722, in __call__
    return cls.__new__(cls, value)
           ~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/enum.py", line 1189, in __new__
    raise ve_exc
ValueError: 'NO DISC' is not a valid PlayStatus
```

It looks like the specification regarding states and status values have changed. I'll read up on the mediaplayer documentation and try if I can figure something out. It will likely impact the `oppoudpsdk` library as well? Need to see how the states are communicated/translated inside the `ha_oppoudp` component. It will likely take me some time though.
